# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20170606_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
